Db constraints
IS-200-G7/nordicdoor pull request #100
Opened 2022-11-02 13:07 UTC by torkelhi

2022-11-02 13:28 UTC, menymo requested changes
Scriptene kjører uten feilmeldinger. Et lite problem angående en ikke-eksisterende defaultverdi, men ellers bra

2022-11-02 13:28 UTC, menymo commented on PDSA_System/Server/DataBase/Create.sql
> +    TeamLederId INTEGER NOT NULL DEFAULT 0,
Jeg hadde ikke satt dette som default. Vi trenger ikke default, da et team skal alltid ha en eksisterende eier.

BrukerId 0 kommer aldri til å eksistere
```suggestion
    TeamLederId INTEGER NOT NULL,
```

2022-11-02 13:29 UTC, torkelhi commented on PDSA_System/Server/DataBase/Create.sql
> +    TeamLederId INTEGER NOT NULL DEFAULT 0,
man får error dersom man gjerner default 0

2022-11-02 13:29 UTC, menymo commented on PDSA_System/Server/DataBase/Create.sql
> +    TeamLederId INTEGER NOT NULL DEFAULT 0,
Men det er fordi `TeamLederId` skal defineres. Team har alltid en eier

2022-11-02 13:30 UTC, torkelhi commented on PDSA_System/Server/DataBase/Create.sql
> +    TeamLederId INTEGER NOT NULL DEFAULT 0,
da må parameterene i team-controller-metoden endres

2022-11-02 13:44 UTC, menymo commented on PDSA_System/Server/DataBase/Create.sql
> +    TeamLederId INTEGER NOT NULL DEFAULT 0,
Mener du `CreateTeam`?
https://github.com/IS-200-G7/nordicdoor/blob/3ff82f7f5f594d0baea79e87d44f20391e168565/PDSA_System/Server/Controllers/TeamController.cs#L52-L64
Den funksjonen henter allerede `TeamLederId` fra objektet man sender inn fra client side. Kan ikke se hvor problemet ligger, med mindre du tenkte på en annen endpoint?

2022-11-02 15:37 UTC, torkelhi commented on PDSA_System/Server/DataBase/Create.sql
> +    TeamLederId INTEGER NOT NULL DEFAULT 0,
Kan se nærmere på det imorgen ?

2022-11-07 11:19 UTC, menymo approved these changes
Fikk ingen uforventede constraintfeil gjennom min testing, ser bra ut

2022-11-07 13:47 UTC, Vrolf commented
Denne er løst av #114.

2022-11-07 13:47 UTC, closed without merging