Rydda koden
IS-200-G7/nordicdoor pull request #125
Opened 2022-11-22 11:34 UTC by sdushantha

Rydda koden slik at ting ser bedre ut for presentasjonen

2022-11-22 11:39 UTC, menymo requested changes, later dismissed
Ser bra ut, men lurer på om du mente å fjerne en controller?

2022-11-22 11:39 UTC, menymo commented on PDSA_System/Server/Controllers/ForslagController.cs
> -    //Metode for å oppdatere Bilde-kolonne i forslag
Skulle denne fjernes?

2022-11-22 11:40 UTC, sdushantha commented on PDSA_System/Server/Controllers/ForslagController.cs
> -    //Metode for å oppdatere Bilde-kolonne i forslag
Det skulle fjernes fordi den ikke blir brukt. Vi endrer på status ved å bruke UpdateForslag kontrolleren

2022-11-23 11:50 UTC, Vrolf approved these changes
Alt funker -. merge for min del :)

2022-11-23 12:07 UTC, merged