Fikset Authorize
IS-200-G7/nordicdoor pull request #126
Opened 2022-11-23 17:43 UTC by sdushantha

Ting funker 👍

2022-11-24 18:40 UTC, torkelhi requested changes

2022-11-24 18:40 UTC, torkelhi commented on PDSA_System/Client/Pages/BrukerAdminPage.razor
> +<AuthorizeView>
Skal ikke dette være Roles = "admin"

2022-11-24 23:08 UTC, sdushantha commented on PDSA_System/Client/Pages/BrukerAdminPage.razor
> +<AuthorizeView>
fikset i ny commit :)

2022-11-24 23:11 UTC, sdushantha commented
fikset merge conflicts
gjerne test PRen på nytt for å fore være 100% at ting funker

2022-11-25 08:15 UTC, torkelhi approved these changes

2022-11-25 08:15 UTC, merged