Create sql update
IS-200-G7/nordicdoor pull request #17
Opened 2022-10-04 09:51 UTC by torkelhi

Bruker(BrukerId) --> gjernet auto_inc

Endret datatype til DATETIME på samtlige i Forslag.

Lagt til Attributt for Kategori --> VARCHAR (150) --> samme lengde som Email-attributt i Bruker-tabell.

2022-10-04 09:57 UTC, sdushantha commented
Er konflikter i koden som på fikses før PRen kan merges

2022-10-04 10:04 UTC, menymo requested changes
Ser bra ut, et lite forslag som jeg tenker vi bør gå gjennom.

Om vi godkjenner forslaget mitt, så bør det definere hvordan vi skriver controllere framover i prosjektet.

2022-10-04 10:04 UTC, menymo commented on PDSA_System/Server/Controllers/BrukerController.cs
> +    [Route("[controller]")]
Kan det være en ide å gjemme slikt bak `/api`? Da får man et mer tydelig skille mellom client og server-side

```suggestion
    [Route("/api/[controller]")]
```

2022-10-04 10:07 UTC, sdushantha commented on PDSA_System/Server/Controllers/BrukerController.cs
> +    [Route("[controller]")]
enig 👍

2022-10-04 15:09 UTC, torkelhi commented
Ny update På pull-request

2022-10-04 15:27 UTC, menymo requested changes
Ser bra ut, ligger noen spørsmål og forslag til endringer her

Trenger ikke merge alt i kveld, men fint om det er mulig med noen svar og kanskje noen enkle "Commit suggestion" for småting

2022-10-04 15:27 UTC, menymo commented on PDSA_System/Server/Controllers/BrukerController.cs
> +        public async Task<ActionResult<List<Bruker>>> DeleteBruker(Bruker bruker, int brukerId)
Greit å fjerne `Bruker` fra parametrene her? Kan ikke se at det har blitt brukt i handler
```suggestion
        public async Task<ActionResult<List<Bruker>>> DeleteBruker(int brukerId)
```

2022-10-04 15:27 UTC, menymo commented on PDSA_System/Server/Program.cs
> +builder.Services.AddSwaggerGen();
Redundant, er definert to linjer lenger ned
```suggestion

```

2022-10-04 15:27 UTC, menymo commented on PDSA_System/Server/PDSA_System.Server.csproj
> +    <PackageReference Include="Dapper" Version="2.0.123" />
Redundant, definert på linje 10
```suggestion

```

2022-10-04 15:27 UTC, menymo commented on PDSA_System/Server/Models/Bruker.cs
> -        }
Er det noe grunn til at constructur er fjernet?

2022-10-04 16:42 UTC, menymo approved these changes
Flott, det med opprettelse av bruker fikser vi til neste sprint-uke. Her er ihvertfall eksempelkode om du har lyst å teste hashing

```
var hasher = new PasswordHash();

var salt = hasher.CreateSalt();
var hash = hasher.HashPassword("DITTPASSORD", salt);

// []byte to base64
var saltBase64 = Convert.ToBase64String(salt);
var hashBase64 = Convert.ToBase64String(hash);
Console.WriteLine($"{hashBase64}:{saltBase64}");
```

2022-10-05 13:09 UTC, EirikBHA commented on PDSA_System/Server/Models/Bruker.cs
> -        }
Ikke brukt i koden, ble forklart på møtet. Tar å resolver denne.

2022-10-05 13:33 UTC, merged