Db fix igjen
IS-200-G7/nordicdoor pull request #63
Opened 2022-10-19 11:36 UTC by menymo

Endringer i forbindelse med refaktorering av roller og introduksjon av `TeamLederId` som FK i `Team`

2022-10-20 11:53 UTC, EirikBHA approved these changes
Is nice

2022-10-20 14:37 UTC, torkelhi commented
Foreslår en endring før merge

2022-10-20 14:40 UTC, torkelhi requested changes

2022-10-20 14:40 UTC, torkelhi commented on PDSA_System/Server/DataBase/Create.sql
>  );
```suggestion
FOREIGN KEY (AvdelingId) REFERENCES Team(TeamId)
);
```
Da er det en unary tilkobling slik vi hadde tenkt. Kan sammenlignes med koblingen mellom bruker og rolle i Bruker-tabellen

2022-10-21 12:12 UTC, torkelhi approved these changes
Testet begge sql filene. Ingen errors. 

Godt jobbet.

2022-10-21 12:12 UTC, merged