Funksjon for å hente ut spesifikke forslag til brukere.
IS-200-G7/nordicdoor pull request #64
Opened 2022-10-19 14:42 UTC by EirikBHA

Hvis test: husk å endre på forfatterId når dere lager forslag;)

2022-10-19 22:38 UTC, tbhansen commented
Veldig bra! Alt fungerer utenom updateforslag, som du har skrevet som kommentar i koden.
Bør tas en gjennomgang av camelcasing slik at stilen er lik som andre controllere. Eks: createforslag -> CreateForslag

2022-10-20 09:33 UTC, menymo requested changes

2022-10-20 09:33 UTC, menymo commented on PDSA_System/Server/Controllers/ForslagController.cs
> +            "UPDATE Forslag SET ForfatterId = @ForfatterId, TeamId = @TeamId, Emne = @Emne, Beskrivelse = @Beskrivelse, Bilde = @Bilde, Kategori = @Kategori WHERE ForslagId = @id", new { id = forslag
Får feilmelding her:
`ForslagController.cs(103, 13): [CS1503] Argument 4: cannot convert from 'PDSA_System.Server.Models.Forslag' to 'System.Data.IDbTransaction'`

2022-10-20 09:34 UTC, EirikBHA commented on PDSA_System/Server/Controllers/ForslagController.cs
> +            "UPDATE Forslag SET ForfatterId = @ForfatterId, TeamId = @TeamId, Emne = @Emne, Beskrivelse = @Beskrivelse, Bilde = @Bilde, Kategori = @Kategori WHERE ForslagId = @id", new { id = forslag
Driver å ser på det mer Torkel nå:)

2022-10-20 10:07 UTC, EirikBHA commented on PDSA_System/Server/Controllers/ForslagController.cs
> +            "UPDATE Forslag SET ForfatterId = @ForfatterId, TeamId = @TeamId, Emne = @Emne, Beskrivelse = @Beskrivelse, Bilde = @Bilde, Kategori = @Kategori WHERE ForslagId = @id", new { id = forslag
Skal funke nå:)

2022-10-20 10:22 UTC, menymo submitted a review, later dismissed

2022-10-20 10:22 UTC, menymo commented on PDSA_System/Server/Controllers/ForslagController.cs
>      [HttpPut("/api/[controller]/updateforslag/{forslagId}")]
Endpoint funker ikke, nærmere beskrevet i #66

2022-10-20 10:22 UTC, menymo commented on PDSA_System/Server/appsettings.json
> +        "DefaultConnection": "server=localhost;user=root;database=NordicTest;port=3306;password=Boksen123;"
👀

2022-10-20 10:23 UTC, EirikBHA commented on PDSA_System/Server/appsettings.json
> +        "DefaultConnection": "server=localhost;user=root;database=NordicTest;port=3306;password=Boksen123;"
Ah, ja

2022-10-20 10:23 UTC, EirikBHA commented on PDSA_System/Server/appsettings.json
> +        "DefaultConnection": "server=localhost;user=root;database=NordicTest;port=3306;password=Boksen123;"
I fix

2022-10-24 07:58 UTC, EirikBHA commented on PDSA_System/Server/Controllers/ForslagController.cs
>      [HttpPut("/api/[controller]/updateforslag/{forslagId}")]
Fikser dette senere i sprint 3.

2022-10-24 08:02 UTC, tbhansen approved these changes
Ok. Issue blir løst ved senere tidspunkt. Merges for å ikke hindre fremgang.

2022-10-24 08:03 UTC, tbhansen approved these changes
Prøver igjen.

2022-10-24 08:06 UTC, merged