DB attributt fix og mer seedData
IS-200-G7/nordicdoor pull request #69
Opened 2022-10-22 11:34 UTC by torkelhi

Create.sql:

Endret default verdi for forslag.opprettet og trigger for forslag.update.

addSeedData.sql:

lagt til flere brukere, teams og forslag. Samt fjerent unødvendig input. Eksempelvis - forslagId som er auto_inc.

2022-10-22 23:32 UTC, menymo requested changes, later dismissed
Ser ganske bra ut, lite forslag angående de nye brukerne som ble lagt til

Synes også at det kunne vært greit å være litt bestemt på om vi skal ha newlines eller ikke mellom de ulike INSERTs. Tenker spesielt på `Team` og `TeamMedlemskap`, men også `ForslagKobling` mens vi er der

2022-10-22 23:32 UTC, menymo commented on PDSA_System/Server/DataBase/addSeedData.sql
> +VALUES (6, 'Eirik', 'Bakkestad', 'bakke@example.no', 'softCactuses', 'ansatt', 5);
Kunne gjerne lagt til fungerende passordhashes i samme slengen, slik at vi har flere brukere å teste ulike scenarioer med

2022-10-23 08:04 UTC, torkelhi commented on PDSA_System/Server/DataBase/addSeedData.sql
> +VALUES (6, 'Eirik', 'Bakkestad', 'bakke@example.no', 'softCactuses', 'ansatt', 5);
Yes, dette kan vi gjøre sammen på mandag?

2022-10-23 08:06 UTC, torkelhi commented on PDSA_System/Server/DataBase/addSeedData.sql
> +VALUES (6, 'Eirik', 'Bakkestad', 'bakke@example.no', 'softCactuses', 'ansatt', 5);
Ift. kommentaren på formateringen av filen så kan vi også bli enig om dette i fellesskap før det blir eventuelt implementert i databasen.

2022-10-23 08:28 UTC, sdushantha commented
> og trigger for forslag.update.

hva mener du med det?

2022-10-23 08:34 UTC, torkelhi commented
> > og trigger for forslag.update.
> 
> hva mener du med det?

default verdi for attributten SistOppdatert er NULL, og endres til Current_Timestamå ved oppdateringer.

2022-10-24 09:37 UTC, Vrolf approved these changes

2022-10-24 09:40 UTC, merged