Endringer på datatyper og returverdier i controllere
IS-200-G7/nordicdoor pull request #94
Opened 2022-11-01 14:59 UTC by menymo

VIktig at dette testes grunndig, både med Swagger og Client

2022-11-01 14:59 UTC, menymo commented
Dette tror jeg skal være alle controllerne som trengte endring, da to av filene ikke hadde noen særlige feil.

Closes #93

2022-11-02 08:44 UTC, EirikBHA requested changes
Dette skulle vel endres?
Commitet rett inn jeg hehe

2022-11-02 08:47 UTC, EirikBHA commented
Fikk også litt problemer med updateforslag:/

2022-11-02 09:08 UTC, menymo commented
> Dette skulle vel endres? Commitet rett inn jeg hehe

Det var i utgangspunktet ikke en del av pull requesten, siden jeg kun tenkte å fikse på datatyper



> Fikk også litt problemer med updateforslag:/

Har du noen logs eller nærmere informasjon om dette?

2022-11-02 09:13 UTC, EirikBHA commented
> > Dette skulle vel endres? Commitet rett inn jeg hehe
> 
> Det var i utgangspunktet ikke en del av pull requesten, siden jeg kun tenkte å fikse på datatyper
> 
Da kan du egt bestemme om du vil ha det med eller ikke i denne PR.
> > Fikk også litt problemer med updateforslag:/
> 
> Har du noen logs eller nærmere informasjon om dette?
Fikk sett på det med Torkel funka likevel:)

2022-11-02 09:44 UTC, torkelhi commented on PDSA_System/Server/Controllers/TeamController.cs
> +            var brukere = await conn.QueryAsync<TeamMedlemskap[]>("SELECT * FROM TeamMedlemskap WHERE TeamId = @id",
SQL

SELECT T.AnsattNr, B.Fornavn, B.Etternavn FROM TeamMedlemskap AS T, Bruker AS B WHERE T.AnsattNr = B.AnsattNr AND T.TeamId = 2;

2022-11-02 12:35 UTC, EirikBHA commented on PDSA_System/Server/Controllers/TeamController.cs
> +            var brukere = await conn.QueryAsync<TeamMedlemskap[]>("SELECT T.AnsattNr, B.Fornavn, B.Etternavn FROM TeamMedlemskap AS T, Bruker AS B WHERE T.AnsattNr = B.AnsattNr AND T.TeamId = @id",
Får feilmelding på denne funksjonen @torkelhi hvordan skal denne fungere?
![image](https://user-images.githubusercontent.com/89193729/199490974-64794455-877a-451c-bfe3-c015166ddda2.png)

2022-11-02 12:42 UTC, torkelhi commented on PDSA_System/Server/Controllers/TeamController.cs
> +            var brukere = await conn.QueryAsync<TeamMedlemskap[]>("SELECT T.AnsattNr, B.Fornavn, B.Etternavn FROM TeamMedlemskap AS T, Bruker AS B WHERE T.AnsattNr = B.AnsattNr AND T.TeamId = @id",
await conn.QueryAsync<TeamMedlemskap[]> er nok problemet. 

Metoden etterspørr flere attributter enn model TeamMedlemskap har.

2022-11-02 13:08 UTC, EirikBHA requested changes
Alt funker bortsett fra GetBrukereFromTeam

2022-11-02 13:31 UTC, EirikBHA approved these changes
It work:,)

2022-11-02 13:31 UTC, merged