Profil page
IS-200-G7/nordicdoor pull request #95
Opened 2022-11-01 15:57 UTC by EirikBHA

Profil side for at brukere kan endre sin info

2022-11-01 16:15 UTC, menymo requested changes
Damn, ingen feilmeldinger

Ligger et lite forslag angående UU, og en liten logisk feil angående passord. Ellers kjempebra

2022-11-01 16:15 UTC, menymo commented on PDSA_System.sln
>  	GlobalSection(SolutionConfigurationPlatforms) = preSolution
Noen grunn til alle disse endringene?

2022-11-01 16:15 UTC, menymo commented on PDSA_System/Server/Controllers/BrukerController.cs
> +                $"UPDATE Bruker SET Fornavn = @Fornavn, Etternavn = @Etternavn, Email = @Email, PassordHash = @PassordHash, LederId = @LederId WHERE AnsattNr = @AnsattNr",
Redundant `$`, kanskje min feil idk
```suggestion
                "UPDATE Bruker SET Fornavn = @Fornavn, Etternavn = @Etternavn, Email = @Email, PassordHash = @PassordHash, LederId = @LederId WHERE AnsattNr = @AnsattNr",
```

2022-11-01 16:15 UTC, menymo commented on PDSA_System/Client/Pages/ProfilPage.razor
> +                    <h4>Du endrer nå din profilinformasjon, er du sikker du vil oppdatere?</h4>
Dette bør ikke være en heading, mtp. WCAG og generelt brukeropplevelse
```suggestion
                    <p>Du endrer nå din profilinformasjon, er du sikker du vil oppdatere?</p>
```

2022-11-01 16:15 UTC, menymo commented on PDSA_System/Server/Controllers/BrukerController.cs
> +                $"UPDATE Bruker SET Fornavn = @Fornavn, Etternavn = @Etternavn, Email = @Email, PassordHash = @PassordHash, LederId = @LederId WHERE AnsattNr = @AnsattNr",
`PUT` overskriver passordhashes, men den skal jo ikke skrives på den måten uansett, da vi har en funksjon for å bytte passord
https://github.com/IS-200-G7/nordicdoor/blob/d119b3e3cbebf0e2f0bdfa67dd93bbaba472afa5/PDSA_System/Server/Controllers/BrukerController.cs#L135-L136
```suggestion
                $"UPDATE Bruker SET Fornavn = @Fornavn, Etternavn = @Etternavn, Email = @Email, LederId = @LederId WHERE AnsattNr = @AnsattNr",
```

2022-11-01 18:48 UTC, EirikBHA commented on PDSA_System.sln
>  	GlobalSection(SolutionConfigurationPlatforms) = preSolution
Hmm, nei kan ikke huske å ha endret bevisst dette. Kan endre tilbake👍

2022-11-01 18:48 UTC, EirikBHA commented on PDSA_System/Server/Controllers/BrukerController.cs
> +                $"UPDATE Bruker SET Fornavn = @Fornavn, Etternavn = @Etternavn, Email = @Email, PassordHash = @PassordHash, LederId = @LederId WHERE AnsattNr = @AnsattNr",
I fix

2022-11-02 11:39 UTC, menymo approved these changes

2022-11-02 11:39 UTC, menymo commented on PDSA_System/Server/Controllers/AuthController.cs
> +using PDSA_System.Shared.Models;
Redundant
```suggestion

```

2022-11-02 11:40 UTC, merged