Forslag rpage
IS-200-G7/nordicdoor pull request #96
Opened 2022-11-01 16:55 UTC by sdushantha

**Hva funker nå:**
- Se alle forslagene
- Lage en forslag
- Trykke på en forslag å se mer info

**Hva må jobbes på:**
- Vise forfatter navn isteden for forfatter ID
- Vise legge til bilder
- Redigere et forslag

2022-11-01 16:59 UTC, menymo commented
Tenker du at det er klart til å merge, eller vil du ha litt tid til å fikse opp i de resterende oppgavene? Må gjerne konvertere til draft dersom det er tilfelle

2022-11-01 17:02 UTC, sdushantha commented
Klar til merging. Jeg skal jobbe på de andre oppgavene senere. Tenkte å bare ha det jeg har nå i master branch

2022-11-01 17:12 UTC, menymo commented
Error ved `POST /createforslag`:

```
System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.Int32.Parse(String s)
   at PDSA_System.Server.Controllers.ForslagController.CreateForslag(Forslag forslag) in /Users/magnus/Projects/PDSA_System/PDSA_System/Server/Controllers/ForslagController.cs:line 80
   at lambda_method24(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

2022-11-01 17:14 UTC, menymo commented
> Error ved `POST /createforslag`:

Legger til mulig løsning til problemet i review

2022-11-01 17:16 UTC, sdushantha commented
Du må logge inn igjen. Gammel JWT token. Samme skjedde med meg nå

2022-11-01 17:25 UTC, menymo requested changes
Ligger et forslag til løsning på problemet med nullverdi. Det bør sjekkes om bruker er logget inn før endpoint antar at det ligger brukerinfo i forespørselen.

Er også en god del unødvendige changes angående whitespace og indentation, som nevnt i #75. Men det er `[Authorize]` som er aller viktigst

2022-11-01 17:25 UTC, menymo commented on PDSA_System/Server/Controllers/ForslagController.cs
>      public async Task<ActionResult<List<Forslag>>> CreateForslag(Forslag forslag)
Dersom bruker ikke er autentisert, får den en 500 som forårsakes en nullverdi i `forfatterId`
```suggestion
    [Authorize]
    public async Task<ActionResult<List<Forslag>>> CreateForslag(Forslag forslag)
```

2022-11-01 20:55 UTC, sdushantha commented
Fikset, klar til merge?

2022-11-01 20:58 UTC, sdushantha commented
@menymo Var din endring som gjorde at vi fikk build fail. Kan du ta en titt på det og fikse?

2022-11-01 21:04 UTC, tbhansen commented
Endringen på linje 76 i ForslagsController failer hos meg
Edit: Så nå at det hadde blitt kommentert av Sidd.
Edit2: Løste seg ved å endre linje 76 til `    [HttpPost("/api/[controller]/createforslag/"), Authorize]`

2022-11-02 09:38 UTC, menymo requested changes

2022-11-02 09:38 UTC, menymo commented on PDSA_System/Server/Controllers/ForslagController.cs
> +    [Authorize]
Må importere `Microsoft.AspNetCore.Authorization`

2022-11-02 12:18 UTC, menymo approved these changes
Når man legger inn forslag, så setter den inn tom string i kategori. Er dette meningen? Fordi det er egentlig nullable i databasen. Seed dataen har også `null` som kategori
```sql
15,5,1,aa,bb,,plan,2022-11-02 12:15:51,,,""
```

Hvis det er det, så er det bare å merge

2022-11-02 12:19 UTC, merged